### ISSUE TITLE
Release 1.1 checklist

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/TilePackageKreator#37]
- [x] Features complete
- [x] Issues marked as verified and closed
- [x] PDF doc link created and added to 
  - [x] repo readme
  - [x] MarketPlace listing
- [x] Release version marked as unrestricted in hockeyapp
- [x] update the links.esri.com links to the new release version
- [x] MarketPlace listing updates
  - [x] Labs listing created
  - [x] Updated version number
- [x] Blogs
  - [x] https://geonet.esri.com/groups/appstudio/blog
  - [x] https://blogs.esri.com/esri/arcgis/
- [x] Update source code available through AppStudio

**Comment by marikavertzonis** [comment]
appstudio blog post is now live
https://geonet.esri.com/groups/appstudio/blog/2017/02/02/tile-package-kreaor-release-11-available-now
