### ISSUE TITLE
Release 1.4 checklist

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/TilePackageKreator#86]
- [x] features complete
- [x] testing complete
- [x] update release version listed on github https://github.com/Esri/TilePackageKreator/releases
- [x] app **submitted** to Windows store
- [x] app **released** in Windows store
- [x] windows, mac and ubuntu desktop app available via public appcenter page (hide old versions)
- [x] make app update available as sample in AppStudio (new online item for appstudio 5.0 only)
- [x] update marketplace listing - https://www.esri.com/en-us/arcgis-marketplace/listing/products/9c9ddae83e5549bb88a2c22e87a18ba1
- [ ] ~geonet blog released~

**Comment by phil-wilson** [comment]
@marikavertzonis 

Tile Package Kreator for Microsoft Store needs a username account and passowrd provided for the release certification, currently they are requesting with following error:

> **Notes To Developer**
> Unfortunately, we can’t test the product because its primary functionality requires a test account, but no test credentials were provided and we can’t create a test account by following the process provided. Please resubmit the product and provide test account information in the Submission Options > Notes for Certification field. This issue may affect merchandisability.
> Tested Devices: Acer Iconia W700, Acer Switch 3

**Comment by phil-wilson** [comment]
@marikavertzonis I resubmitted and provided the Apple_Test AGO username/password and also the instructions your provided me, good news, review complete and successfully published in the store.

https://www.microsoft.com/store/apps/9PM0RRBMCSRZ
