### ISSUE TITLE
Release 1.5 checklist

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/TilePackageKreator#91]
- [x] features complete
- [x] testing complete
- [x] update release version listed on github https://github.com/Esri/TilePackageKreator/releases
- [x] app **submitted** to Windows store
- [x] app **released** in Windows store
- [x] windows, mac and ubuntu desktop app available via public appcenter page (hide old versions)
- [x] make app update available as sample in AppStudio (new online item for appstudio 5.0 only)
- [x] update marketplace listing - https://www.esri.com/en-us/arcgis-marketplace/listing/products/9c9ddae83e5549bb88a2c22e87a18ba1
- [ ] ~geonet blog released~

**Comment by marikavertzonis** [comment]
issue to update public access versions https://devtopia.esri.com/Melbourne/DevOps/issues/381
